`timescale 1ns/1ps
// =============================================================================
// Module : MB_DESERIALIZER_FRAMED   (Option-A data lane — lives in unsued/)
// =============================================================================
// Data-lane DDR deserializer that takes its word boundary from the framing
// master (MB_DESERIALIZER_VALID) instead of free-running an internal counter.
//
//   * DDR pairing is the fixed scheme from unsued/mb_deserializer.sv: shift on
//     the NEGEDGE, pairing the live LOW-phase bit (ser_data_in = word[2n+1])
//     with the even bit captured this cycle's posedge (r_data_pos = word[2n]).
//   * It shifts continuously while ser_data_en is high and latches a completed
//     32-bit word ONLY when i_word_load is asserted. i_word_load is generated by
//     the master on the pll_clk POSEDGE and is therefore stable when this
//     negedge block samples it -> no cross-module delta race.
//
// Because every lane shifts in lockstep on the same pll_clk with the same enable
// and latches on the same shared i_word_load, all 16 lanes capture exactly on
// the valid-frame boundary by construction. The original per-lane bit counter is
// gone (the master owns framing).
// =============================================================================
module MB_DESERIALIZER_FRAMED #(
    parameter DATA_WIDTH = 32
)(
    input  wire                   MB_clk,
    input  wire                   pll_clk,
    input  wire                   i_rst_n,
    input  wire                   ser_data_en,
    input  wire                   ser_data_in,
    input  wire                   i_word_load,    // framing strobe from the master
    output reg  [DATA_WIDTH-1:0]  par_data_out,
    output reg                    de_ser_done
);

    reg [DATA_WIDTH-1:0] shift_reg;
    reg [DATA_WIDTH-1:0] save_data;

    // CDC handshake (pll_clk -> MB_clk)
    reg  save_data_toggle;
    reg  sync1_toggle, sync2_toggle, sync3_toggle;
    wire valid_pulse;

    // even bit captured on rising edge
    reg r_data_pos;
    always @(posedge pll_clk or negedge i_rst_n) begin
        if (!i_rst_n)            r_data_pos <= 1'b0;
        else if (ser_data_en)    r_data_pos <= ser_data_in;   // word[2n]
    end

    // shift every cycle, latch only when the master says the word is complete
    always @(negedge pll_clk or negedge i_rst_n) begin
        if (!i_rst_n) begin
            shift_reg        <= {DATA_WIDTH{1'b0}};
            save_data        <= {DATA_WIDTH{1'b0}};
            save_data_toggle <= 1'b0;
        end else if (ser_data_en) begin
            shift_reg <= {ser_data_in, r_data_pos, shift_reg[DATA_WIDTH-1:2]};
            if (i_word_load) begin
                save_data        <= {ser_data_in, r_data_pos, shift_reg[DATA_WIDTH-1:2]};
                save_data_toggle <= ~save_data_toggle;
            end
        end
    end

    // CDC pll_clk -> MB_clk
    always @(posedge MB_clk or negedge i_rst_n) begin
        if (!i_rst_n) begin
            sync1_toggle <= 1'b0;
            sync2_toggle <= 1'b0;
            sync3_toggle <= 1'b0;
        end else begin
            sync1_toggle <= save_data_toggle;
            sync2_toggle <= sync1_toggle;
            sync3_toggle <= sync2_toggle;
        end
    end
    assign valid_pulse = (sync2_toggle != sync3_toggle);

    always @(posedge MB_clk or negedge i_rst_n) begin
        if (!i_rst_n) begin
            par_data_out <= {DATA_WIDTH{1'b0}};
            de_ser_done  <= 1'b0;
        end else begin
            de_ser_done <= 1'b0;        // 1-cycle pulse
            if (valid_pulse) begin
                par_data_out <= save_data;
                de_ser_done  <= 1'b1;
            end
        end
    end

endmodule
