onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Link_Controller_tb/clk
add wave -noupdate /Link_Controller_tb/vif/clk
add wave -noupdate /Link_Controller_tb/vif/rst_n
add wave -noupdate /Link_Controller_tb/vif/Link_msg_send
add wave -noupdate /Link_Controller_tb/vif/Link_vld_send
add wave -noupdate /Link_Controller_tb/vif/Adapter_msg_send
add wave -noupdate /Link_Controller_tb/vif/Adapter_vld_send
add wave -noupdate /Link_Controller_tb/vif/ser_ready
add wave -noupdate /Link_Controller_tb/vif/Adapter_ready
add wave -noupdate /Link_Controller_tb/vif/Link_ready
add wave -noupdate /Link_Controller_tb/vif/des_data_rcvd
add wave -noupdate /Link_Controller_tb/vif/des_vld_rcvd
add wave -noupdate /Link_Controller_tb/vif/pattern_mode
add wave -noupdate /Link_Controller_tb/vif/start_pat_req
add wave -noupdate /Link_Controller_tb/vif/send_4_iter
add wave -noupdate /Link_Controller_tb/vif/four_iter_done
add wave -noupdate /Link_Controller_tb/vif/det_pat_rcvd
add wave -noupdate /Link_Controller_tb/vif/ser_data_send
add wave -noupdate /Link_Controller_tb/vif/ser_vld_send
add wave -noupdate /Link_Controller_tb/vif/Adapter_msg_rcvd
add wave -noupdate /Link_Controller_tb/vif/Adapter_vld_rcvd
add wave -noupdate /Link_Controller_tb/vif/LINK_msg_rcvd
add wave -noupdate /Link_Controller_tb/vif/Link_valid_rcvd
add wave -noupdate /Link_Controller_tb/vif/mapper_ready
add wave -noupdate /Link_Controller_tb/dut/clk
add wave -noupdate /Link_Controller_tb/dut/rst_n
add wave -noupdate /Link_Controller_tb/dut/Link_msg_send
add wave -noupdate /Link_Controller_tb/dut/Link_vld_send
add wave -noupdate /Link_Controller_tb/dut/Adapter_msg_send
add wave -noupdate /Link_Controller_tb/dut/Adapter_vld_send
add wave -noupdate /Link_Controller_tb/dut/ser_ready
add wave -noupdate /Link_Controller_tb/dut/pattern_mode
add wave -noupdate /Link_Controller_tb/dut/start_pat_req
add wave -noupdate /Link_Controller_tb/dut/send_4_iter
add wave -noupdate /Link_Controller_tb/dut/four_iter_done
add wave -noupdate /Link_Controller_tb/dut/ser_data_send
add wave -noupdate /Link_Controller_tb/dut/ser_vld_send
add wave -noupdate /Link_Controller_tb/dut/Adapter_ready
add wave -noupdate /Link_Controller_tb/dut/Link_ready
add wave -noupdate /Link_Controller_tb/dut/det_pat_rcvd
add wave -noupdate /Link_Controller_tb/dut/des_data_rcvd
add wave -noupdate /Link_Controller_tb/dut/des_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/Adapter_msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/Adapter_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/LINK_msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/Link_valid_rcvd
add wave -noupdate /Link_Controller_tb/dut/msg_word_rcvd
add wave -noupdate /Link_Controller_tb/dut/word_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/word_vld_send
add wave -noupdate /Link_Controller_tb/dut/msg_word_send
add wave -noupdate /Link_Controller_tb/dut/mapper_ready
add wave -noupdate /Link_Controller_tb/dut/msg_send
add wave -noupdate /Link_Controller_tb/dut/msg_vld_send
add wave -noupdate /Link_Controller_tb/dut/msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/msg_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/msg_path_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Link_msg_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Link_vld_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Link_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Adapter_msg_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Adapter_vld_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/Adapter_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/mapper_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/msg_word_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/word_vld_send
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/hp_msg
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/hp_vld
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/hp_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/lp_msg
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/lp_vld
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/lp_ready
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/out_msg
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/out_vld
add wave -noupdate /Link_Controller_tb/dut/u_Link_Arbiter/u_sb_priority_arbiter/out_ready
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/msg_word_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/word_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/Adapter_msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/Adapter_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/Link_msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/Link_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_LINK_Demux/msg_dist
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/clk
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/rst_n
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/msg_word_send
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/word_vld_send
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/ser_ready
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/mapper_ready
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/msg_send
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/msg_vld_send
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/second_half_reg
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/current_state
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/next_state
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/opcode
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/is_128bit
add wave -noupdate /Link_Controller_tb/dut/u_sb_mapper/arb_fire
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/clk
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/rst_n
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/msg_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/msg_word_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/word_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/opcode
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/is_128bit
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/first_half_reg
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/current_state
add wave -noupdate /Link_Controller_tb/dut/u_DEMAPPER/next_state
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/clk
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/rst_n
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/pattern_mode
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/des_data_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/des_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/det_pat_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/msg_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/msg_vld_rcvd
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/is_pattern
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_detector/pattern_cnt
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/clk
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/rst_n
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/pattern_mode
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/start_pat_req
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/send_4_iter
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/four_iter_done
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/mapper_data
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/mapper_valid
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/mapper_ready
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/ser_ready
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/ser_data
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/ser_valid
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/state
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/next_state
add wave -noupdate /Link_Controller_tb/dut/u_sb_pattern_engine/iter_cnt
add wave -noupdate /std::mailbox::mailbox__1::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__1::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__1::try_get/message
add wave -noupdate /std::mailbox::mailbox__1::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__1::try_peek/message
add wave -noupdate /std::mailbox::mailbox__2::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__2::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__2::try_get/message
add wave -noupdate /std::mailbox::mailbox__2::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__2::try_peek/message
add wave -noupdate /std::mailbox::mailbox__3::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__3::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__3::try_get/message
add wave -noupdate /std::mailbox::mailbox__3::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__3::try_peek/message
add wave -noupdate /std::mailbox::mailbox__4::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__4::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__4::try_get/message
add wave -noupdate /std::mailbox::mailbox__4::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__4::try_peek/message
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5261 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {5232 ns} {5424 ns}
