// =============================================================================
// Testbench : MB_TOP_tb
// DUT       : MB_TOP  (MB_TX_TOP looped back to MB_RX_TOP)
// Timescale : 1ps / 1ps  (PLL at 2 GHz → 500 ps period)
//
// Test sequence
// ─────────────
//  Phase 1 — CLK Pattern Gen (TX) + CLK Pattern Detector (RX)
//  Phase 2 — VALID Pattern TX → RX valid detector
//  Phase 3 — LFSR Training
//            3a: CLEAR_LFSR (reset both LFSR seeds)
//            3b: PATTERN_LFSR  → expect zero bit errors
//            3c: PER_LANE_ID   → expect zero lane ID errors
//  Phase 4 — DATA_TRANSFER: Mapper sends data, Demapper receives
//
// Clock note
// ──────────
//  o_pll_clk : 500 ps (2 GHz), generated by DUT's MB_PLL
//  o_mb_clk  : 8000 ps (125 MHz) = o_pll_clk / 16 (ClkDiv inside DUT)
//  TB drives no clock — all synchronisation uses DUT output clocks.
// =============================================================================

`timescale 1ps/1ps

module MB_TOP_tb;

// =========================================================================
// Parameters
// =========================================================================
localparam DATA_WIDTH = 32;
localparam NUM_LANES  = 16;
localparam N_BYTES    = 64;

// LTSM state encodings (mirror LFSR_TX / LFSR_RX localparam)
localparam [2:0] ST_IDLE         = 3'b000;
localparam [2:0] ST_CLEAR_LFSR   = 3'b001;
localparam [2:0] ST_PAT_LFSR     = 3'b010;
localparam [2:0] ST_PER_LANE_ID  = 3'b011;
localparam [2:0] ST_DATA         = 3'b100;

// All 16 lanes active
localparam [2:0] W_ALL16 = 3'b011;

// Timeouts (in domain cycles)
localparam int TO_PLL_CLK  = 6000;   // Phase 1 CLK pattern  (~3072 pos-edges)
localparam int TO_MB_VALID = 200;    // Phase 2 VALID done
localparam int TO_MB_LFSR  = 600;    // Phase 3 LFSR/ID done
localparam int TO_MB_ERR   = 600;    // Wait for pattern comparator
localparam int TO_MB_DATA  = 300;    // Phase 4 pl_valid

// Watchdog
localparam longint WD_PS = 600_000_000; // 600 µs

// =========================================================================
// DUT interface signals
// =========================================================================
// — reset & PLL
logic                    i_rst_n          = 0;
logic                    i_pll_en         = 0;
logic [1:0]              i_pll_speed_sel  = 2'b00;

// — shared LTSM
logic [2:0]              i_ltsm_state          = ST_IDLE;
logic                    i_active_state_entered = 0;
logic [2:0]              i_width_deg            = W_ALL16;

// — TX controls
logic                    i_clk_pattern_en  = 0;
logic                    i_clk_embedded_en = 0;
logic                    i_valid_pattern_en= 0;
logic                    i_reversal_en     = 0;
logic [8*N_BYTES-1:0]    i_raw_data        = 0;
logic                    i_mapper_en       = 0;
logic                    i_lp_irdy         = 0;
logic                    i_lp_valid        = 0;

// — RX controls
logic                    clk_detector_en   = 0;
logic                    i_descramble_en   = 0;
logic                    i_enable_buffer   = 0;
logic [11:0]             i_max_err_valid   = 12'd0;
logic                    i_enable_cons     = 0;
logic                    i_enable_128      = 0;
logic                    i_enable_detector = 0;
logic [1:0]              i_type_of_com     = 2'b01;   // per-lane comparison
logic [15:0]             i_max_err_per_lane= 16'd0;   // zero errors allowed
logic [15:0]             i_max_err_agg     = 16'd0;
logic                    demapper_en       = 0;
logic                    rx_data_valid     = 0;

// — DUT outputs
logic                    o_pll_clk;
logic                    o_mb_clk;
logic                    o_clk_done;
logic                    o_valid_done;
logic                    o_lfsr_tx_done;
logic                    o_mapper_ready;
logic                    de_ser_done;
logic                    detection_result;
logic                    o_valid_frame_detect;
logic [15:0]             o_per_lane_error;
logic [31:0]             o_error_counter;
logic                    o_error_done;
logic                    clk_p_pattern_pass;
logic                    clk_n_pattern_pass;
logic                    track_pattern_pass;
logic                    pl_valid;
logic [8*N_BYTES-1:0]    o_out_data;

// =========================================================================
// Test bookkeeping
// =========================================================================
int test_num   = 0;
int pass_count = 0;
int fail_count = 0;

// =========================================================================
// DUT
// =========================================================================
MB_TOP #(
    .DATA_WIDTH (DATA_WIDTH),
    .NUM_LANES  (NUM_LANES),
    .N_BYTES    (N_BYTES)
) dut (
    .i_rst_n                (i_rst_n),
    .i_pll_en               (i_pll_en),
    .i_pll_speed_sel        (i_pll_speed_sel),
    .i_ltsm_state           (i_ltsm_state),
    .i_active_state_entered (i_active_state_entered),
    .i_width_deg            (i_width_deg),
    .i_clk_pattern_en       (i_clk_pattern_en),
    .i_clk_embedded_en      (i_clk_embedded_en),
    .i_valid_pattern_en     (i_valid_pattern_en),
    .i_reversal_en          (i_reversal_en),
    .i_raw_data             (i_raw_data),
    .i_mapper_en            (i_mapper_en),
    .i_lp_irdy              (i_lp_irdy),
    .i_lp_valid             (i_lp_valid),
    .clk_detector_en        (clk_detector_en),
    .i_descramble_en        (i_descramble_en),
    .i_enable_buffer        (i_enable_buffer),
    .i_max_err_valid        (i_max_err_valid),
    .i_enable_cons          (i_enable_cons),
    .i_enable_128           (i_enable_128),
    .i_enable_detector      (i_enable_detector),
    .i_type_of_com          (i_type_of_com),
    .i_max_err_per_lane     (i_max_err_per_lane),
    .i_max_err_agg          (i_max_err_agg),
    .demapper_en            (demapper_en),
    .rx_data_valid          (rx_data_valid),
    .o_pll_clk              (o_pll_clk),
    .o_mb_clk               (o_mb_clk),
    .o_clk_done             (o_clk_done),
    .o_valid_done           (o_valid_done),
    .o_lfsr_tx_done         (o_lfsr_tx_done),
    .o_mapper_ready         (o_mapper_ready),
    .de_ser_done            (de_ser_done),
    .detection_result       (detection_result),
    .o_valid_frame_detect   (o_valid_frame_detect),
    .o_per_lane_error       (o_per_lane_error),
    .o_error_counter        (o_error_counter),
    .o_error_done           (o_error_done),
    .clk_p_pattern_pass     (clk_p_pattern_pass),
    .clk_n_pattern_pass     (clk_n_pattern_pass),
    .track_pattern_pass     (track_pattern_pass),
    .pl_valid               (pl_valid),
    .o_out_data             (o_out_data)
);

// =========================================================================
// Helper tasks
// =========================================================================

// --- wait N posedges on o_pll_clk ---
task automatic wait_pll(input int n);
    repeat (n) @(posedge o_pll_clk);
endtask

// --- wait N posedges on o_mb_clk ---
task automatic wait_mb(input int n);
    repeat (n) @(posedge o_mb_clk);
endtask

// --- wait for sig == 1, sampling o_pll_clk, with timeout ---
task automatic wait_sig_pll(
    input  string name,
    ref    logic  sig,
    input  int    timeout_cyc
);
    int cnt = 0;
    @(posedge o_pll_clk); // align
    while (!sig && cnt < timeout_cyc) begin
        @(posedge o_pll_clk);
        cnt++;
    end
    if (cnt >= timeout_cyc && !sig) begin
        $display("  [TIMEOUT] %s not seen after %0d pll cycles  (t=%0t ps)",
                 name, timeout_cyc, $time);
        fail_count++;
    end
endtask

// --- wait for sig == 1, sampling o_mb_clk, with timeout ---
task automatic wait_sig_mb(
    input  string name,
    ref    logic  sig,
    input  int    timeout_cyc
);
    int cnt = 0;
    @(posedge o_mb_clk); // align
    while (!sig && cnt < timeout_cyc) begin
        @(posedge o_mb_clk);
        cnt++;
    end
    if (cnt >= timeout_cyc && !sig) begin
        $display("  [TIMEOUT] %s not seen after %0d mb cycles  (t=%0t ps)",
                 name, timeout_cyc, $time);
        fail_count++;
    end
endtask

// --- self-checking assertion ---
task automatic check(input string desc, input logic cond);
    if (cond) begin
        $display("  [PASS] %s", desc);
        pass_count++;
    end else begin
        $display("  [FAIL] %s", desc);
        fail_count++;
    end
endtask

// =========================================================================
// Monitors  (always-on, print key events as they happen)
// =========================================================================
always @(posedge o_pll_clk) begin
    if (o_clk_done)
        $display("      [MON-PLL] o_clk_done  t=%0t ps", $time);
end

always @(posedge o_mb_clk) begin
    if (o_valid_done)
        $display("      [MON-MB]  o_valid_done         t=%0t ps", $time);
    if (o_lfsr_tx_done)
        $display("      [MON-MB]  o_lfsr_tx_done       t=%0t ps", $time);
    if (de_ser_done)
        $display("      [MON-MB]  de_ser_done          t=%0t ps", $time);
    if (o_error_done)
        $display("      [MON-MB]  o_error_done  per_lane=%04h  agg=%0d  t=%0t ps",
                 o_per_lane_error, o_error_counter, $time);
    if (detection_result)
        $display("      [MON-MB]  detection_result=1   t=%0t ps", $time);
    if (pl_valid)
        $display("      [MON-MB]  pl_valid  out[63:0]=%016h  t=%0t ps",
                 o_out_data[63:0], $time);
    if (o_mapper_ready)
        $display("      [MON-MB]  o_mapper_ready       t=%0t ps", $time);
end

// =========================================================================
// Watchdog
// =========================================================================
initial begin
    #(WD_PS);
    $display("\n[WATCHDOG] Simulation exceeded %0d ps — terminating.\n", WD_PS);
    $display("  PASS: %0d   FAIL: %0d (watchdog counts as FAIL)", pass_count, fail_count+1);
    $finish;
end

// =========================================================================
// Main stimulus
// =========================================================================
initial begin : tb_main
    $display("=============================================================");
    $display("  MB_TOP Integration Testbench  —  UCIe 3.0 Main-Band");
    $display("  Speed: 2 GHz PLL  |  Width: x16  |  div_ratio: 16");
    $display("  o_pll_clk = 500 ps  |  o_mb_clk = 8000 ps");
    $display("=============================================================\n");

    // ─────────────────────────────────────────────────────────────────────
    // Power-on: enable PLL while reset is still asserted
    // ─────────────────────────────────────────────────────────────────────
    i_pll_en       = 1;
    i_pll_speed_sel= 2'b00;   // 2 GHz
    i_rst_n        = 0;

    // Wait for PLL to produce its first clock edge
    @(posedge o_pll_clk);
    wait_pll(20);             // Let PLL stabilise

    // Release reset — ClkDiv starts counting after this
    @(posedge o_pll_clk);
    i_rst_n = 1;
    $display("[TB] Reset released at t=%0t ps\n", $time);

    // Wait for o_mb_clk first posedge (16 PLL cycles after reset release)
    @(posedge o_mb_clk);
    wait_mb(4);               // A few mb_clk cycles to settle

    // =====================================================================
    // PHASE 1 — CLK Pattern Generation & Detection
    // =====================================================================
    test_num = 1;
    $display("─────────────────────────────────────────────────────────────");
    $display("[Test 1] CLK Pattern Generation + Pattern Detection  t=%0t ps", $time);
    $display("─────────────────────────────────────────────────────────────");

    @(negedge o_mb_clk);
    i_clk_pattern_en = 1;
    clk_detector_en  = 1;

    // TX: wait for CLK burst to complete
    // CLK_PATTERN_GEN_TX fires on both edges → ~3072 posedges for 128-burst
    wait_sig_pll("o_clk_done", o_clk_done, TO_PLL_CLK);

    i_clk_pattern_en = 0;

    // Give RX CLK detector enough cycles to count its 16 consecutive matches
    wait_mb(40);

    check("clk_p  pattern pass", clk_p_pattern_pass);
    check("clk_n  pattern pass", clk_n_pattern_pass);
    check("track  pattern pass", track_pattern_pass);

    clk_detector_en = 0;
    $display("");

    // =====================================================================
    // PHASE 2 — VALID Pattern TX → RX
    // =====================================================================
    test_num = 2;
    $display("─────────────────────────────────────────────────────────────");
    $display("[Test 2] VALID Pattern  (TX → RX detection)  t=%0t ps", $time);
    $display("─────────────────────────────────────────────────────────────");
    // CONSEC_16 mode: 16 consecutive frames of 0x0F0F0F0F → detection_result=1
    // VALID_TX drives 33 mb_clk cycles of valid pattern → plenty of frames

    @(negedge o_mb_clk);
    i_enable_cons     = 1;
    i_enable_detector = 1;
    i_valid_pattern_en= 1;

    // Wait for TX done (33 mb_clk cycles max)
    wait_sig_mb("o_valid_done", o_valid_done, TO_MB_VALID);
    @(posedge o_mb_clk);
    i_valid_pattern_en = 0;

    // Extra cycles: deserializer CDC + detector counting
    wait_mb(60);

    check("VALID detected  (detection_result=1)", detection_result);

    i_enable_cons     = 0;
    i_enable_detector = 0;
    $display("");

    // =====================================================================
    // PHASE 3 — LFSR Training
    // =====================================================================
    test_num = 3;
    $display("─────────────────────────────────────────────────────────────");
    $display("[Test 3] LFSR Training  t=%0t ps", $time);
    $display("─────────────────────────────────────────────────────────────");

    // ── 3a: CLEAR_LFSR — reset both TX and RX LFSR seeds ────────────────
    $display("  [3a] CLEAR_LFSR");
    @(negedge o_mb_clk);
    i_ltsm_state = ST_CLEAR_LFSR;
    wait_mb(3);                      // CLEAR is single-cycle; hold briefly
    i_ltsm_state = ST_IDLE;
    wait_mb(2);

    // ── 3b: PATTERN_LFSR ─────────────────────────────────────────────────
    $display("  [3b] PATTERN_LFSR");
    @(negedge o_mb_clk);
    i_ltsm_state           = ST_PAT_LFSR;
    i_enable_buffer        = 1;      // Allows LFSR_RX to advance per received word
    i_type_of_com          = 2'b01;  // per-lane
    i_max_err_per_lane     = 16'd0;
    i_max_err_agg          = 16'd0;

    // Wait for TX LFSR phase to complete
    wait_sig_mb("o_lfsr_tx_done (PATTERN_LFSR)", o_lfsr_tx_done, TO_MB_LFSR);
    @(posedge o_mb_clk);
    i_ltsm_state = ST_IDLE;

    // Wait for RX pattern comparator to finish its 128-iteration check
    wait_sig_mb("o_error_done (PATTERN_LFSR)", o_error_done, TO_MB_ERR);

    check("PATTERN_LFSR: o_per_lane_error == 0", (o_per_lane_error === 16'h0000));
    check("PATTERN_LFSR: o_error_counter  == 0", (o_error_counter  === 32'h0000_0000));
    wait_mb(2);

    // ── 3c: PER_LANE_ID ──────────────────────────────────────────────────
    $display("  [3c] PER_LANE_ID");
    @(negedge o_mb_clk);
    i_ltsm_state = ST_PER_LANE_ID;

    wait_sig_mb("o_lfsr_tx_done (PER_LANE_ID)", o_lfsr_tx_done, TO_MB_LFSR);
    @(posedge o_mb_clk);
    i_ltsm_state = ST_IDLE;

    wait_sig_mb("o_error_done (PER_LANE_ID)", o_error_done, TO_MB_ERR);

    check("PER_LANE_ID: o_per_lane_error == 0", (o_per_lane_error === 16'h0000));
    check("PER_LANE_ID: o_error_counter  == 0", (o_error_counter  === 32'h0000_0000));

    i_enable_buffer = 0;
    $display("");

    // =====================================================================
    // PHASE 4 — DATA_TRANSFER (Mapper → serial lanes → Demapper)
    // =====================================================================
    test_num = 4;
    $display("─────────────────────────────────────────────────────────────");
    $display("[Test 4] DATA_TRANSFER: Mapper → Demapper loopback  t=%0t ps", $time);
    $display("─────────────────────────────────────────────────────────────");

    begin : data_phase
        // Known 512-bit test word: bytes 0x01, 0x02, ... 0x40
        automatic logic [8*N_BYTES-1:0] tx_word;
        int b;
        for (b = 0; b < N_BYTES; b++)
            tx_word[b*8 +: 8] = 8'(b + 1);

        i_raw_data = tx_word;
        $display("  TX word [63:0]  = %016h", i_raw_data[63:0]);
        $display("  TX word [127:64]= %016h", i_raw_data[127:64]);

        @(negedge o_mb_clk);

        // Enter active state on both TX and RX simultaneously
        i_ltsm_state           = ST_DATA;
        i_active_state_entered = 1;
        i_mapper_en            = 1;
        i_lp_irdy              = 1;
        i_lp_valid             = 1;
        i_descramble_en        = 1;  // RX descrambles
        i_enable_buffer        = 1;
        demapper_en            = 1;
        rx_data_valid          = 1;

        // Wait for mapper to accept data
        wait_sig_mb("o_mapper_ready", o_mapper_ready, 30);

        // Keep driving for a few cycles to fill the serializer pipeline
        wait_mb(5);
        i_lp_irdy  = 0;
        i_lp_valid = 0;

        // Wait for RX demapper to produce output
        wait_sig_mb("pl_valid", pl_valid, TO_MB_DATA);

        // Checks: pipeline is alive and data arrived
        check("pl_valid fired (Demapper produced output)", pl_valid);
        check("o_out_data != 0  (non-zero data reached Demapper)", (o_out_data !== 0));

        // Deassert active state
        @(posedge o_mb_clk);
        i_active_state_entered = 0;
        i_ltsm_state           = ST_IDLE;
        i_mapper_en            = 0;
        demapper_en            = 0;
        rx_data_valid          = 0;
        i_enable_buffer        = 0;
        i_descramble_en        = 0;
    end
    $display("");

    // =====================================================================
    // Summary
    // =====================================================================
    wait_mb(5);

    $display("=============================================================");
    $display("  SIMULATION COMPLETE  —  t = %0t ps", $time);
    $display("  PASS : %0d", pass_count);
    $display("  FAIL : %0d", fail_count);
    $display("=============================================================");
    if (fail_count == 0)
        $display("  *** ALL TESTS PASSED ***\n");
    else
        $display("  *** %0d TEST(S) FAILED ***\n", fail_count);

    $finish;
end : tb_main

endmodule
