// ===========================================================================
//  Reg_File
//  UCIe PHY Register Block – Chapter 9 "Configuration and Parameters"
//
//  Register organisation (UCIe §9.5):
//   The D22/PHY Register Block is 8 KB.
//   First 4 KB  (0000h–0FFFh) belongs to the D2D Adapter.
//   Second 4 KB (1000h–1FFFh) belongs to the Physical Layer (this file).
//
//  All addresses presented to this module are the full 24-bit addresses
//  from the sideband packet.  Only the range 1000h–10FFh is decoded here.
//  Accesses outside this range return rf_rdata = 0 with rdata_vld = 1 and
//  an UR status is generated by the FSM.
//
//  Register summary implemented (UCIe §9.5.x):
//  ─────────────────────────────────────────────────────────────────────────
//  Offset  Reg name             Access  Width  Description (spec reference)
//  ─────────────────────────────────────────────────────────────────────────
//  1000h   PHY Capability       RO      32     §9.5.1  – Package type, max speed
//  1004h   PHY Control          RW      32     §9.5.2  – Rx term, Tx EQ, etc.
//  1008h   PHY Status           RO      32     §9.5.24 – Link state, clk mode
//  100Ch   Training Control     RW      32     §9.5.x  – MBINIT/MBTRAIN cfg
//  1010h   Rx Training Config   RW      32     §9.5.x  – Vref sweep params
//  1020h   Tx Training Config   RW      32     §9.5.x  – Tx EQ preset control
//  1030h   Lane Map 0           RW      32     §9.5.x  – Lane reversal / map
//  1040h   Lane Map 1           RW      32     §9.5.x  – Upper lane mapping
//  1050h   Link Speed Config    RW      32     §9.5.x  – Target link speed
//  1060h   MBINIT Param Config  RW      64     §9.5.x  – MBINIT negotiation cfg
//  1068h   MBTRAIN Config       RW      32     §9.5.x  – Training timeouts
//  1070h   Error Status         RW1C    32     §9.5.x  – Sticky error bits
//  1078h   Error Enable         RW      32     §9.5.x  – Error interrupt enables
//  1080h   Error Log 0          ROS     32     §9.5.34 – Training state at err
//  1084h   Error Log 1          ROS     32     §9.5.x  – Previous state N-1
//  1088h   Error Log 2          ROS     32     §9.5.x  – Previous state N-2
//  ─────────────────────────────────────────────────────────────────────────
//
//  For PHY Status (1008h) and Error Log 0 (1080h) the register values are
//  driven externally by the LTSM/RDI state machines via the status_i port.
// ===========================================================================

module Reg_File (
    input  logic         clk,
    input  logic         rst_n,

    // -----------------------------------------------------------------------
    // Register-access interface (from Reg_Access_FSM)
    // -----------------------------------------------------------------------
    input  logic [23:0]  rf_addr,    // Byte address from request
    input  logic [7:0]   rf_be,      // Byte enables [7:0]
    input  logic [63:0]  rf_wdata,   // Write data (up to 64 bits)
    input  logic         rd_en,      // Read strobe
    input  logic         wr_en,      // Write strobe

    output logic [63:0]  rf_rdata,   // Read-data (combinatorial or 1-cycle)
    output logic         rdata_vld,  // Data-valid (registered, 1-cycle delay)

    // -----------------------------------------------------------------------
    // Live status inputs from PHY state machines
    // UCIe §9.5.24 – PHY Status is driven by the LTSM, not written via SB
    // UCIe §9.5.34 – Error Log 0 captures the training state at error
    // -----------------------------------------------------------------------
    input  logic [7:0]   phy_link_state,   // Current LTSM state encoding
    input  logic         phy_rx_term,      // Rx termination enabled
    input  logic         phy_tx_eq,        // Tx EQ active
    input  logic         phy_clk_mode,     // 0=strobe 1=free-running
    input  logic         phy_clk_phase,    // 0=differential 1=quadrature
    input  logic         phy_lane_rev,     // Lane reversal within module

    // Error log capture (write-once on error; cleared on reset)
    input  logic [7:0]   err_state_capture,// State when error occurred
    input  logic         err_capture_en,   // Pulse to latch error log

    // -----------------------------------------------------------------------
    // Readable outputs for other blocks (convenience taps)
    // -----------------------------------------------------------------------
    output logic         rx_term_en,       // From PHY_CONTROL[0]
    output logic         tx_eq_en,         // From PHY_CONTROL[1]
    output logic         retrain_req       // From PHY_CONTROL[2]
);

// ===========================================================================
//  Register storage
// ===========================================================================

// --- PHY Capability (1000h) – RO -------------------------------------------
// UCIe §9.5.1 Table 9-1
// [0]   Standard Package supported      = 1'b1 (always in this implementation)
// [1]   Advanced Package supported      = implementation specific
// [3:2] Num Modules (00=1, 01=2, …)    = 2'b00 (single module)
// [7:4] Max Data Rate
//        4'b0001 = 4  GT/s
//        4'b0010 = 8  GT/s
//        4'b0100 = 16 GT/s
//        4'b1000 = 32 GT/s (maximum, hardwired per chip choice)
// [15:8] Rx Clock Modes supported (per MBINIT.PARAM negotiation)
// [31:16] Reserved (RsvdZ)
logic [31:0] phy_capability;
assign phy_capability = 32'h0000_0401;
//  Bits[0]=1 (Standard package), Bits[7:4]=4'b0100 (max 16 GT/s capability)

// --- PHY Control (1004h) – RW -----------------------------------------------
// UCIe §9.5.2 Table 9-2
// [0]   Rx Termination Enable (0=disabled; 1=enabled, default=0)
// [1]   Tx EQ Enable          (0=disabled; 1=enabled, default=0)
// [2]   Retrain Request       (0=no action; 1=request retrain, self-clearing)
// [5:3] Force Link Speed      (000=no force, see speed encoding)
// [6]   Force Lane Reversal   (0=no force; 1=force reversal)
// [31:7] Reserved (RsvdZ)
logic [31:0] phy_control_r;

// --- PHY Status (1008h) – RO (driven externally) ----------------------------
// UCIe §9.5.24 – Table 9-49:
// [2:0]  Reserved (RO)
// [3]    Rx Termination Status (0=disabled; 1=enabled)
// [4]    Tx EQ Status          (0=disabled; 1=enabled)
// [5]    Clock Mode Status     (0=strobe; 1=free-running)
// [6]    Clock Phase Status    (0=differential; 1=quadrature)
// [7]    Lane Reversal within Module
// [18:8] Reserved (RO)
// [26:19] Link State encoding  (§9.5.34 state encoding table)
// [31:27] Reserved
logic [31:0] phy_status;
always_comb begin
    phy_status      = '0;
    phy_status[3]   = phy_rx_term;
    phy_status[4]   = phy_tx_eq;
    phy_status[5]   = phy_clk_mode;
    phy_status[6]   = phy_clk_phase;
    phy_status[7]   = phy_lane_rev;
    phy_status[26:19] = {phy_link_state};
end

// --- Training Control (100Ch) – RW ------------------------------------------
// UCIe §9.5.x – internal: controls MBINIT/MBTRAIN entry conditions
// [0]    Enable MBINIT CAL
// [1]    Enable MBTRAIN VALVREF
// [2]    Enable MBTRAIN DATAVREF
// [7:3]  Reserved (RsvdZ)
// [15:8] Training timeout multiplier (units of 100 µs)
// [31:16] Reserved (RsvdZ)
logic [31:0] training_control_r;

// --- Rx Training Config (1010h) – RW ----------------------------------------
// UCIe §9.5.x – Vref sweep start/stop/step
// [5:0]   Vref Start value
// [11:6]  Vref Stop  value
// [15:12] Vref Step  size
// [31:16] Reserved
logic [31:0] rx_training_cfg_r;

// --- Tx Training Config (1020h) – RW ----------------------------------------
// UCIe §9.5.x – Tx EQ preset selection
// [3:0]   Tx EQ Preset index
// [31:4]  Reserved
logic [31:0] tx_training_cfg_r;

// --- Lane Map 0 (1030h) – RW ------------------------------------------------
// UCIe §9.5.x – lower lane reversal/mapping bitmap
logic [31:0] lane_map0_r;

// --- Lane Map 1 (1040h) – RW ------------------------------------------------
// UCIe §9.5.x – upper lane mapping
logic [31:0] lane_map1_r;

// --- Link Speed Config (1050h) – RW -----------------------------------------
// UCIe §9.5.x
// [3:0] Target link speed (same encoding as PHY Capability speed field)
// [31:4] Reserved
logic [31:0] link_speed_cfg_r;

// --- MBINIT Param Config (1060h) – RW 64-bit --------------------------------
// UCIe §9.5.x – advertised parameters sent during MBINIT.PARAM exchange
// [63:0] Configuration word (format mirrors MsgInfo/payload in MBINIT.PARAM)
logic [63:0] mbinit_param_cfg_r;

// --- MBTRAIN Config (1068h) – RW --------------------------------------------
// UCIe §9.5.x – training timeout and retry config
// [15:0]  Timeout count (units = cycles)
// [23:16] Max retry count
// [31:24] Reserved
logic [31:0] mbtrain_cfg_r;

// --- Error Status (1070h) – RW1C -------------------------------------------
// UCIe §9.5.x – sticky error status bits; write 1 to clear
// [0]  Parity error detected
// [1]  Unsupported Request received
// [2]  Training timeout
// [3]  Link error detected
// [31:4] Reserved
logic [31:0] error_status_r;

// --- Error Enable (1078h) – RW ----------------------------------------------
// UCIe §9.5.x – enables individual error interrupt sources
// [0]  Parity error enable
// [1]  UR error enable
// [2]  Training timeout enable
// [3]  Link error enable
// [31:4] Reserved
logic [31:0] error_enable_r;

// --- Error Log 0 (1080h) – ROS ----------------------------------------------
// UCIe §9.5.34 – "Captures the current Link training state machine status.
//  State Encodings: 00h RESET … 17h ACTIVE … 18h TRAINERROR …"
// [7:0]   State N   (state at time of error)
// [8]     Lane Reversal within module
// [9]     Width Degrade
// [15:10] Reserved
// [23:16] State N-1
// [31:24] State N-2
logic [31:0] error_log0_r;

// --- Error Log 1 / 2 (1084h / 1088h) – ROS --------------------------------
logic [31:0] error_log1_r;
logic [31:0] error_log2_r;

// ===========================================================================
//  Write logic  (synchronous, byte-enable aware)
// ===========================================================================
always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        phy_control_r     <= 32'h0000_0000;
        training_control_r<= 32'h0000_0003;  // default: CAL+VALVREF enabled
        rx_training_cfg_r <= 32'h0000_0000;
        tx_training_cfg_r <= 32'h0000_0000;
        lane_map0_r       <= 32'h0000_0000;
        lane_map1_r       <= 32'h0000_0000;
        link_speed_cfg_r  <= 32'h0000_0004;  // default: 16 GT/s target
        mbinit_param_cfg_r<= 64'h0000_0000_0000_0000;
        mbtrain_cfg_r     <= 32'h0001_03E8;  // timeout=1000 cycles, maxretry=1
        error_status_r    <= 32'h0000_0000;
        error_enable_r    <= 32'h0000_000F;  // all sources enabled by default
        error_log0_r      <= 32'h0000_0000;
        error_log1_r      <= 32'h0000_0000;
        error_log2_r      <= 32'h0000_0000;
    end else begin

        // ---------------------------------------------------------------
        // Register write path – byte-enable granularity
        // ---------------------------------------------------------------
        if (wr_en) begin
            case (rf_addr[11:0])  // use lower 12 bits (offset within PHY block)

                12'h004: begin   // PHY Control (1004h)
                    if (rf_be[0]) phy_control_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) phy_control_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) phy_control_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) phy_control_r[31:24] <= rf_wdata[31:24];
                end

                12'h00C: begin   // Training Control (100Ch)
                    if (rf_be[0]) training_control_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) training_control_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) training_control_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) training_control_r[31:24] <= rf_wdata[31:24];
                end

                12'h010: begin   // Rx Training Config (1010h)
                    if (rf_be[0]) rx_training_cfg_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) rx_training_cfg_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) rx_training_cfg_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) rx_training_cfg_r[31:24] <= rf_wdata[31:24];
                end

                12'h020: begin   // Tx Training Config (1020h)
                    if (rf_be[0]) tx_training_cfg_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) tx_training_cfg_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) tx_training_cfg_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) tx_training_cfg_r[31:24] <= rf_wdata[31:24];
                end

                12'h030: begin   // Lane Map 0 (1030h)
                    if (rf_be[0]) lane_map0_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) lane_map0_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) lane_map0_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) lane_map0_r[31:24] <= rf_wdata[31:24];
                end

                12'h040: begin   // Lane Map 1 (1040h)
                    if (rf_be[0]) lane_map1_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) lane_map1_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) lane_map1_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) lane_map1_r[31:24] <= rf_wdata[31:24];
                end

                12'h050: begin   // Link Speed Config (1050h)
                    if (rf_be[0]) link_speed_cfg_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) link_speed_cfg_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) link_speed_cfg_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) link_speed_cfg_r[31:24] <= rf_wdata[31:24];
                end

                12'h060: begin   // MBINIT Param Config low 32 (1060h)
                    if (rf_be[0]) mbinit_param_cfg_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) mbinit_param_cfg_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) mbinit_param_cfg_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) mbinit_param_cfg_r[31:24] <= rf_wdata[31:24];
                    // 64-bit access also writes upper half
                    if (rf_be[4]) mbinit_param_cfg_r[39:32] <= rf_wdata[39:32];
                    if (rf_be[5]) mbinit_param_cfg_r[47:40] <= rf_wdata[47:40];
                    if (rf_be[6]) mbinit_param_cfg_r[55:48] <= rf_wdata[55:48];
                    if (rf_be[7]) mbinit_param_cfg_r[63:56] <= rf_wdata[63:56];
                end

                12'h068: begin   // MBTRAIN Config (1068h)
                    if (rf_be[0]) mbtrain_cfg_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) mbtrain_cfg_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) mbtrain_cfg_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) mbtrain_cfg_r[31:24] <= rf_wdata[31:24];
                end

                12'h070: begin   // Error Status – RW1C (1070h)
                    // UCIe §9.5: write 1 clears the bit
                    if (rf_be[0]) error_status_r[7:0]   <= error_status_r[7:0]   & ~rf_wdata[7:0];
                    if (rf_be[1]) error_status_r[15:8]  <= error_status_r[15:8]  & ~rf_wdata[15:8];
                    if (rf_be[2]) error_status_r[23:16] <= error_status_r[23:16] & ~rf_wdata[23:16];
                    if (rf_be[3]) error_status_r[31:24] <= error_status_r[31:24] & ~rf_wdata[31:24];
                end

                12'h078: begin   // Error Enable (1078h)
                    if (rf_be[0]) error_enable_r[7:0]   <= rf_wdata[7:0];
                    if (rf_be[1]) error_enable_r[15:8]  <= rf_wdata[15:8];
                    if (rf_be[2]) error_enable_r[23:16] <= rf_wdata[23:16];
                    if (rf_be[3]) error_enable_r[31:24] <= rf_wdata[31:24];
                end

                // Error Log registers are ROS – not written by software
                default: ; // Address not mapped → silently ignore write
            endcase
        end

        // ---------------------------------------------------------------
        // Hardware writes: error log capture (ROS – read-only sticky)
        // UCIe §9.5.34: "Captures the current Link training state machine
        // status.  Default is 0."
        // ---------------------------------------------------------------
        if (err_capture_en) begin
            // Shift history: N-2 ← N-1 ← N ← new
            error_log0_r[31:24] <= error_log0_r[23:16];  // N-2
            error_log0_r[23:16] <= error_log0_r[7:0];    // N-1
            error_log0_r[7:0]   <= err_state_capture;    // State N
        end

        // ---------------------------------------------------------------
        // Self-clearing bits
        // ---------------------------------------------------------------
        // PHY_CONTROL[2] = retrain_req is self-clearing after one cycle
        if (phy_control_r[2])
            phy_control_r[2] <= 1'b0;

    end  // else (not reset)
end

// ===========================================================================
//  Read logic  (1-cycle registered)
// ===========================================================================
always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        rf_rdata  <= '0;
        rdata_vld <= 1'b0;
    end else if (rd_en) begin
        rdata_vld <= 1'b1;

        case (rf_addr[11:0])
            12'h000: rf_rdata <= {32'h0, phy_capability};
            12'h004: rf_rdata <= {32'h0, phy_control_r};
            12'h008: rf_rdata <= {32'h0, phy_status};
            12'h00C: rf_rdata <= {32'h0, training_control_r};
            12'h010: rf_rdata <= {32'h0, rx_training_cfg_r};
            12'h020: rf_rdata <= {32'h0, tx_training_cfg_r};
            12'h030: rf_rdata <= {32'h0, lane_map0_r};
            12'h040: rf_rdata <= {32'h0, lane_map1_r};
            12'h050: rf_rdata <= {32'h0, link_speed_cfg_r};
            12'h060: rf_rdata <= mbinit_param_cfg_r;        // 64-bit
            12'h068: rf_rdata <= {32'h0, mbtrain_cfg_r};
            12'h070: rf_rdata <= {32'h0, error_status_r};
            12'h078: rf_rdata <= {32'h0, error_enable_r};
            12'h080: rf_rdata <= {32'h0, error_log0_r};
            12'h084: rf_rdata <= {32'h0, error_log1_r};
            12'h088: rf_rdata <= {32'h0, error_log2_r};
            default: rf_rdata <= 64'h0000_0000_DEAD_BEEF;   // unmapped
        endcase
    end else if (wr_en) begin
        // Write path also needs rdata_vld so FSM can proceed
        rdata_vld <= 1'b1;
        rf_rdata  <= '0;
    end else begin
        rdata_vld <= 1'b0;
        rf_rdata  <= '0;
    end
end

// ===========================================================================
//  Convenience output taps
// ===========================================================================
assign rx_term_en  = phy_control_r[0];
assign tx_eq_en    = phy_control_r[1];
assign retrain_req = phy_control_r[2];

endmodule
