flowchart TD
VALVREF_PTR_IDLE(["VALVREF_PTR_IDLE"])
VALVREF_PTR_WAIT_START_REQ(["VALVREF_PTR_WAIT_START_REQ"])
VALVREF_PTR_SEND_START_RESP(["VALVREF_PTR_SEND_START_RESP"])
VALVREF_PTR_WAIT_END_REQ(["VALVREF_PTR_WAIT_END_REQ"])
VALVREF_PTR_SEND_END_RESP(["VALVREF_PTR_SEND_END_RESP"])
VALVREF_PTR_TO_DATAVREF(["VALVREF_PTR_TO_DATAVREF"])
START2((" "))

START2 --> VALVREF_PTR_IDLE
VALVREF_PTR_IDLE -->|"valvref_en == 1"| VALVREF_PTR_WAIT_START_REQ
VALVREF_PTR_WAIT_START_REQ -->|"rx_sb_msg == MBTRAIN_VALVREF_start_req (d35)"| VALVREF_PTR_SEND_START_RESP
VALVREF_PTR_SEND_START_RESP -->|"unconditionally (1 cycle pulse)"| VALVREF_PTR_WAIT_END_REQ
VALVREF_PTR_WAIT_END_REQ -->|"rx_sb_msg == MBTRAIN_VALVREF_end_req (d37)"| VALVREF_PTR_SEND_END_RESP
VALVREF_PTR_SEND_END_RESP -->|"unconditionally (1 cycle pulse)"| VALVREF_PTR_TO_DATAVREF
VALVREF_PTR_TO_DATAVREF -->|"valvref_en == 0"| VALVREF_PTR_IDLE
