flowchart TD
SPEEDIDLE_PTR_IDLE(["SPEEDIDLE_PTR_IDLE"])
SPEEDIDLE_PTR_TO_TRAINERROR(["SPEEDIDLE_PTR_TO_TRAINERROR"])
SPEEDIDLE_PTR_CONFIG(["SPEEDIDLE_PTR_CONFIG"])
SPEEDIDLE_PTR_WAIT_REQ(["SPEEDIDLE_PTR_WAIT_REQ"])
SPEEDIDLE_PTR_SEND_RESP(["SPEEDIDLE_PTR_SEND_RESP"])
SPEEDIDLE_PTR_DONE(["SPEEDIDLE_PTR_DONE"])
START2((" "))

START2 --> SPEEDIDLE_PTR_IDLE
SPEEDIDLE_PTR_IDLE -->|"speedidle_en == 1 && speed_degrade_error == 1"| SPEEDIDLE_PTR_TO_TRAINERROR
SPEEDIDLE_PTR_IDLE -->|"speedidle_en == 1 && speed_degrade_error == 0"| SPEEDIDLE_PTR_CONFIG
SPEEDIDLE_PTR_CONFIG -->|"unconditionally (1 cycle)"| SPEEDIDLE_PTR_WAIT_REQ
SPEEDIDLE_PTR_WAIT_REQ -->|"rx_sb_msg == MBTRAIN_SPEEDIDLE_done_req (d43)"| SPEEDIDLE_PTR_SEND_RESP
SPEEDIDLE_PTR_SEND_RESP -->|"unconditionally (1 cycle pulse)"| SPEEDIDLE_PTR_DONE
SPEEDIDLE_PTR_DONE -->|"speedidle_en == 0"| SPEEDIDLE_PTR_IDLE
SPEEDIDLE_PTR_TO_TRAINERROR -->|"speedidle_en == 0"| SPEEDIDLE_PTR_IDLE
