flowchart TD
TXSELFCAL_PTR_IDLE(["TXSELFCAL_PTR_IDLE"])
TXSELFCAL_PTR_WAIT_REQ(["TXSELFCAL_PTR_WAIT_REQ"])
TXSELFCAL_PTR_SEND_RESP(["TXSELFCAL_PTR_SEND_RESP"])
TXSELFCAL_PTR_DONE(["TXSELFCAL_PTR_DONE"])
START2((" "))

START2 --> TXSELFCAL_PTR_IDLE
TXSELFCAL_PTR_IDLE -->|"txselfcal_en == 1"| TXSELFCAL_PTR_WAIT_REQ
TXSELFCAL_PTR_WAIT_REQ -->|"rx_sb_msg == MBTRAIN_TXSELFCAL_Done_req (d45)"| TXSELFCAL_PTR_SEND_RESP
TXSELFCAL_PTR_SEND_RESP -->|"unconditionally (1 cycle pulse)"| TXSELFCAL_PTR_DONE
TXSELFCAL_PTR_DONE -->|"txselfcal_en == 0"| TXSELFCAL_PTR_IDLE
