flowchart TD
IQ_LCL_IDLE(["IQ_LCL_IDLE"])
IQ_LCL_MEASURE(["IQ_LCL_MEASURE"])
IQ_LCL_EVAL(["IQ_LCL_EVAL"])
IQ_LCL_DONE_SUCCESS(["IQ_LCL_DONE_SUCCESS"])
IQ_LCL_SEND_SHIFT_REQ(["IQ_LCL_SEND_SHIFT_REQ"])
IQ_LCL_WAIT_RESP(["IQ_LCL_WAIT_RESP"])
IQ_LCL_DONE_ERROR(["IQ_LCL_DONE_ERROR"])
IQ_LCL_SETTLE(["IQ_LCL_SETTLE"])
START2((" "))

START2 --> IQ_LCL_IDLE
IQ_LCL_IDLE -->|"iq_en == 1"| IQ_LCL_MEASURE
IQ_LCL_MEASURE -->|"analog_settle_time_done == 1"| IQ_LCL_EVAL
IQ_LCL_EVAL -->|"phy_rx_tckn_shift == 0"| IQ_LCL_DONE_SUCCESS
IQ_LCL_EVAL -->|"phy_rx_tckn_shift != 0"| IQ_LCL_SEND_SHIFT_REQ
IQ_LCL_SEND_SHIFT_REQ -->|"unconditionally (1 cycle pulse)"| IQ_LCL_WAIT_RESP
IQ_LCL_WAIT_RESP -->|"rx_sb_msg == MBTRAIN_RXCLKCAL_TCKN_L_shift_resp && rx_msginfo[0] == 1"| IQ_LCL_DONE_ERROR
IQ_LCL_WAIT_RESP -->|"rx_sb_msg == MBTRAIN_RXCLKCAL_TCKN_L_shift_resp && rx_msginfo[0] == 0"| IQ_LCL_SETTLE
IQ_LCL_SETTLE -->|"analog_settle_time_done == 1"| IQ_LCL_MEASURE
IQ_LCL_DONE_SUCCESS -->|"iq_en == 0"| IQ_LCL_IDLE
IQ_LCL_DONE_ERROR -->|"iq_en == 0"| IQ_LCL_IDLE
