flowchart TD
RXCLKCAL_PTR_IDLE(["RXCLKCAL_PTR_IDLE"])
RXCLKCAL_PTR_WAIT_START_REQ(["RXCLKCAL_PTR_WAIT_START_REQ"])
RXCLKCAL_PTR_SEND_START_RESP(["RXCLKCAL_PTR_SEND_START_RESP"])
RXCLKCAL_PTR_IQ_LOOP(["RXCLKCAL_PTR_IQ_LOOP"])
RXCLKCAL_PTR_TO_TRAINERROR(["RXCLKCAL_PTR_TO_TRAINERROR"])
RXCLKCAL_PTR_SEND_DONE_RESP(["RXCLKCAL_PTR_SEND_DONE_RESP"])
RXCLKCAL_PTR_TO_VALTRAINCENTER(["RXCLKCAL_PTR_TO_VALTRAINCENTER"])
START3((" "))

START3 --> RXCLKCAL_PTR_IDLE
RXCLKCAL_PTR_IDLE -->|"rxclkcal_en == 1"| RXCLKCAL_PTR_WAIT_START_REQ
RXCLKCAL_PTR_WAIT_START_REQ -->|"rx_sb_msg == MBTRAIN_RXCLKCAL_start_req (d47)"| RXCLKCAL_PTR_SEND_START_RESP
RXCLKCAL_PTR_SEND_START_RESP -->|"unconditionally (1 cycle pulse)"| RXCLKCAL_PTR_IQ_LOOP
RXCLKCAL_PTR_IQ_LOOP -->|"iq_partner_done == 1 && iq_partner_error == 1"| RXCLKCAL_PTR_TO_TRAINERROR
RXCLKCAL_PTR_IQ_LOOP -->|"iq_partner_done == 1 && iq_partner_error == 0"| RXCLKCAL_PTR_SEND_DONE_RESP
RXCLKCAL_PTR_SEND_DONE_RESP -->|"unconditionally (1 cycle pulse)"| RXCLKCAL_PTR_TO_VALTRAINCENTER
RXCLKCAL_PTR_TO_VALTRAINCENTER -->|"rxclkcal_en == 0"| RXCLKCAL_PTR_IDLE
RXCLKCAL_PTR_TO_TRAINERROR -->|"rxclkcal_en == 0"| RXCLKCAL_PTR_IDLE
