flowchart TD
RXCLKCAL_LCL_IDLE(["RXCLKCAL_LCL_IDLE"])
RXCLKCAL_LCL_SEND_START_REQ(["RXCLKCAL_LCL_SEND_START_REQ"])
RXCLKCAL_LCL_WAIT_START_RESP(["RXCLKCAL_LCL_WAIT_START_RESP"])
RXCLKCAL_LCL_INIT_LOCK(["RXCLKCAL_LCL_INIT_LOCK"])
RXCLKCAL_LCL_IQ_LOOP(["RXCLKCAL_LCL_IQ_LOOP"])
RXCLKCAL_LCL_SEND_DONE_REQ(["RXCLKCAL_LCL_SEND_DONE_REQ"])
RXCLKCAL_LCL_TO_TRAINERROR(["RXCLKCAL_LCL_TO_TRAINERROR"])
RXCLKCAL_LCL_WAIT_DONE_RESP(["RXCLKCAL_LCL_WAIT_DONE_RESP"])
RXCLKCAL_LCL_TO_VALTRAINCENTER(["RXCLKCAL_LCL_TO_VALTRAINCENTER"])
START1((" "))

START1 --> RXCLKCAL_LCL_IDLE
RXCLKCAL_LCL_IDLE -->|"rxclkcal_en == 1"| RXCLKCAL_LCL_SEND_START_REQ
RXCLKCAL_LCL_SEND_START_REQ -->|"unconditionally (1 cycle pulse)"| RXCLKCAL_LCL_WAIT_START_RESP
RXCLKCAL_LCL_WAIT_START_RESP -->|"rx_sb_msg == MBTRAIN_RXCLKCAL_start_resp (d48)"| RXCLKCAL_LCL_INIT_LOCK
RXCLKCAL_LCL_INIT_LOCK -->|"analog_settle_time_done == 1 && is_high_speed == 1"| RXCLKCAL_LCL_IQ_LOOP
RXCLKCAL_LCL_INIT_LOCK -->|"analog_settle_time_done == 1 && is_high_speed == 0"| RXCLKCAL_LCL_SEND_DONE_REQ
RXCLKCAL_LCL_IQ_LOOP -->|"iq_done == 1 && iq_error == 1"| RXCLKCAL_LCL_TO_TRAINERROR
RXCLKCAL_LCL_IQ_LOOP -->|"iq_done == 1 && iq_error == 0"| RXCLKCAL_LCL_SEND_DONE_REQ
RXCLKCAL_LCL_SEND_DONE_REQ -->|"unconditionally (1 cycle pulse)"| RXCLKCAL_LCL_WAIT_DONE_RESP
RXCLKCAL_LCL_WAIT_DONE_RESP -->|"rx_sb_msg == MBTRAIN_RXCLKCAL_done_resp (d52)"| RXCLKCAL_LCL_TO_VALTRAINCENTER
RXCLKCAL_LCL_TO_VALTRAINCENTER -->|"rxclkcal_en == 0"| RXCLKCAL_LCL_IDLE
RXCLKCAL_LCL_TO_TRAINERROR -->|"rxclkcal_en == 0"| RXCLKCAL_LCL_IDLE
