flowchart TD
VALTRAINVREF_PTR_IDLE(["VALTRAINVREF_PTR_IDLE"])
VALTRAINVREF_PTR_WAIT_START_REQ(["VALTRAINVREF_PTR_WAIT_START_REQ"])
VALTRAINVREF_PTR_SEND_START_RESP(["VALTRAINVREF_PTR_SEND_START_RESP"])
VALTRAINVREF_PTR_WAIT_END_REQ(["VALTRAINVREF_PTR_WAIT_END_REQ"])
VALTRAINVREF_PTR_SEND_END_RESP(["VALTRAINVREF_PTR_SEND_END_RESP"])
VALTRAINVREF_PTR_TO_DATATRAINCENTER1(["VALTRAINVREF_PTR_TO_DATATRAINCENTER1"])
START2((" "))

START2 --> VALTRAINVREF_PTR_IDLE
VALTRAINVREF_PTR_IDLE -->|"valtrainvref_en == 1"| VALTRAINVREF_PTR_WAIT_START_REQ
VALTRAINVREF_PTR_WAIT_START_REQ -->|"rx_sb_msg == MBTRAIN_VALTRAINVREF_start_req (d57)"| VALTRAINVREF_PTR_SEND_START_RESP
VALTRAINVREF_PTR_SEND_START_RESP -->|"unconditionally (1 cycle pulse)"| VALTRAINVREF_PTR_WAIT_END_REQ
VALTRAINVREF_PTR_WAIT_END_REQ -->|"rx_sb_msg == MBTRAIN_VALTRAINVREF_end_req (d59)"| VALTRAINVREF_PTR_SEND_END_RESP
VALTRAINVREF_PTR_SEND_END_RESP -->|"unconditionally (1 cycle pulse)"| VALTRAINVREF_PTR_TO_DATATRAINCENTER1
VALTRAINVREF_PTR_TO_DATATRAINCENTER1 -->|"valtrainvref_en == 0"| VALTRAINVREF_PTR_IDLE
