sequenceDiagram
    participant Local
    participant Partner

    Note over Local: SEND_START_REQ
    rect rgb(240,240,255)
        Note over Partner: WAIT_START_REQ
        Local->>Partner: DATATRAINCENTER1_start_req (d61)
        Note over Local: WAIT_START_RESP
        Note over Partner: SEND_START_RESP
        Partner-->>Local: DATATRAINCENTER1_start_resp (d62)
    end
    rect rgb(240,255,240)
        Note over Local: SWEEP
        Note over Partner: WAIT_END_REQ
        Note over Local,Partner: Data sweep completes <br/> latches best midpoint codes
        Note over Local: SEND_END_REQ
    end
    rect rgb(255,240,240)
        Local->>Partner: DATATRAINCENTER1_end_req (d63)
        Note over Local: WAIT_END_RESP
        Note over Partner: SEND_END_RESP
        Partner-->>Local: DATATRAINCENTER1_end_resp (d64)
    end
    Note over Local: TO_DATATRAINVREF
    Note over Partner: TO_DATATRAINVREF
