flowchart TD
DATATRAINVREF_LCL_IDLE(["DATATRAINVREF_LCL_IDLE"])
DATATRAINVREF_LCL_SEND_START_REQ(["DATATRAINVREF_LCL_SEND_START_REQ"])
DATATRAINVREF_LCL_WAIT_START_RESP(["DATATRAINVREF_LCL_WAIT_START_RESP"])
DATATRAINVREF_LCL_SWEEP(["DATATRAINVREF_LCL_SWEEP"])
DATATRAINVREF_LCL_APPLY_BEST(["DATATRAINVREF_LCL_APPLY_BEST"])
DATATRAINVREF_LCL_SEND_END_REQ(["DATATRAINVREF_LCL_SEND_END_REQ"])
DATATRAINVREF_LCL_WAIT_END_RESP(["DATATRAINVREF_LCL_WAIT_END_RESP"])
DATATRAINVREF_LCL_TO_RXDESKEW(["DATATRAINVREF_LCL_TO_RXDESKEW"])
START1((" "))

START1 --> DATATRAINVREF_LCL_IDLE
DATATRAINVREF_LCL_IDLE -->|"datatrainvref_en == 1"| DATATRAINVREF_LCL_SEND_START_REQ
DATATRAINVREF_LCL_SEND_START_REQ -->|"unconditionally (1 cycle pulse)"| DATATRAINVREF_LCL_WAIT_START_RESP
DATATRAINVREF_LCL_WAIT_START_RESP -->|"rx_sb_msg == MBTRAIN_DATATRAINVREF_start_resp (d66)"| DATATRAINVREF_LCL_SWEEP
DATATRAINVREF_LCL_SWEEP -->|"sweep_done == 1"| DATATRAINVREF_LCL_APPLY_BEST
DATATRAINVREF_LCL_APPLY_BEST -->|"unconditionally (1 cycle)"| DATATRAINVREF_LCL_SEND_END_REQ
DATATRAINVREF_LCL_SEND_END_REQ -->|"unconditionally (1 cycle pulse)"| DATATRAINVREF_LCL_WAIT_END_RESP
DATATRAINVREF_LCL_WAIT_END_RESP -->|"rx_sb_msg == MBTRAIN_DATATRAINVREF_end_resp (d68)"| DATATRAINVREF_LCL_TO_RXDESKEW
DATATRAINVREF_LCL_TO_RXDESKEW -->|"datatrainvref_en == 0"| DATATRAINVREF_LCL_IDLE
