flowchart TD
RXDESKEW_PTR_IDLE(["RXDESKEW_PTR_IDLE"])
RXDESKEW_PTR_WAIT_START_REQ(["RXDESKEW_PTR_WAIT_START_REQ"])
RXDESKEW_PTR_SEND_START_RESP(["RXDESKEW_PTR_SEND_START_RESP"])
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ(["RXDESKEW_PTR_WAIT_SWEEP_OR_REQ"])
RXDESKEW_PTR_SEND_PRESET_RESP(["RXDESKEW_PTR_SEND_PRESET_RESP"])
RXDESKEW_PTR_SEND_PRESET_FAIL(["RXDESKEW_PTR_SEND_PRESET_FAIL"])
RXDESKEW_PTR_SEND_EXIT_DTC1_RESP(["RXDESKEW_PTR_SEND_EXIT_DTC1_RESP"])
RXDESKEW_PTR_TO_TRAINERROR(["RXDESKEW_PTR_TO_TRAINERROR"])
RXDESKEW_PTR_SEND_END_RESP(["RXDESKEW_PTR_SEND_END_RESP"])
RXDESKEW_PTR_DTC1_ARC_INC(["RXDESKEW_PTR_DTC1_ARC_INC"])
RXDESKEW_PTR_TO_DTC1(["RXDESKEW_PTR_TO_DTC1"])
RXDESKEW_PTR_TO_DTC2(["RXDESKEW_PTR_TO_DTC2"])
END2((" "))
START2((" "))

START2 --> RXDESKEW_PTR_IDLE
RXDESKEW_PTR_IDLE -->|"rxdeskew_en == 1"| RXDESKEW_PTR_WAIT_START_REQ
RXDESKEW_PTR_WAIT_START_REQ -->|"rx_sb_msg == MBTRAIN_RXDESKEW_start_req (d69)"| RXDESKEW_PTR_SEND_START_RESP
RXDESKEW_PTR_SEND_START_RESP -->|"unconditionally (1 cycle pulse)"| RXDESKEW_PTR_WAIT_SWEEP_OR_REQ
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ -->|"rx_sb_msg == Preset_req (d89) && preset <= 5"| RXDESKEW_PTR_SEND_PRESET_RESP
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ -->|"rx_sb_msg == Preset_req (d89) && preset > 5"| RXDESKEW_PTR_SEND_PRESET_FAIL
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ -->|"rx_sb_msg == exit_to_DATATRAINCENTER1_req (d73) && dtc1_arc_cnt < 4"| RXDESKEW_PTR_SEND_EXIT_DTC1_RESP
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ -->|"rx_sb_msg == exit_to_DATATRAINCENTER1_req (d73) && dtc1_arc_cnt >= 4"| RXDESKEW_PTR_TO_TRAINERROR
RXDESKEW_PTR_WAIT_SWEEP_OR_REQ -->|"(rx_sb_msg == end_req (d75) || end_req_rcvd) && !local_exit_dtc1_active && local_end_active"| RXDESKEW_PTR_SEND_END_RESP
RXDESKEW_PTR_SEND_PRESET_RESP -->|"unconditionally (1 cycle pulse)"| RXDESKEW_PTR_WAIT_SWEEP_OR_REQ
RXDESKEW_PTR_SEND_PRESET_FAIL -->|"unconditionally (1 cycle pulse)"| RXDESKEW_PTR_WAIT_SWEEP_OR_REQ
RXDESKEW_PTR_SEND_EXIT_DTC1_RESP -->|"unconditionally (1 cycle pulse)"| RXDESKEW_PTR_DTC1_ARC_INC
RXDESKEW_PTR_DTC1_ARC_INC -->|"unconditionally (1 cycle)"| RXDESKEW_PTR_TO_DTC1
RXDESKEW_PTR_SEND_END_RESP -->|"unconditionally (1 cycle pulse)"| RXDESKEW_PTR_TO_DTC2
RXDESKEW_PTR_TO_DTC2 -->|"rxdeskew_en == 0"| END2
RXDESKEW_PTR_TO_DTC1 -->|"rxdeskew_en == 0"| END2
RXDESKEW_PTR_TO_TRAINERROR -->|"rxdeskew_en == 0"| END2
