flowchart TD
DATATRAINCENTER2_PTR_IDLE(["DATATRAINCENTER2_PTR_IDLE"])
DATATRAINCENTER2_PTR_WAIT_START_REQ(["DATATRAINCENTER2_PTR_WAIT_START_REQ"])
DATATRAINCENTER2_PTR_SEND_START_RESP(["DATATRAINCENTER2_PTR_SEND_START_RESP"])
DATATRAINCENTER2_PTR_WAIT_END_REQ(["DATATRAINCENTER2_PTR_WAIT_END_REQ"])
DATATRAINCENTER2_PTR_SEND_END_RESP(["DATATRAINCENTER2_PTR_SEND_END_RESP"])
DATATRAINCENTER2_PTR_TO_LINKSPEED(["DATATRAINCENTER2_PTR_TO_LINKSPEED"])
END2((" "))
START2((" "))

START2 --> DATATRAINCENTER2_PTR_IDLE
DATATRAINCENTER2_PTR_IDLE -->|"datatraincenter2_en == 1"| DATATRAINCENTER2_PTR_WAIT_START_REQ
DATATRAINCENTER2_PTR_WAIT_START_REQ -->|"rx_sb_msg == MBTRAIN_DATATRAINCENTER2_start_req (d77)"| DATATRAINCENTER2_PTR_SEND_START_RESP
DATATRAINCENTER2_PTR_SEND_START_RESP -->|"unconditionally (1 cycle pulse)"| DATATRAINCENTER2_PTR_WAIT_END_REQ
DATATRAINCENTER2_PTR_WAIT_END_REQ -->|"rx_sb_msg == MBTRAIN_DATATRAINCENTER2_end_req (d79)"| DATATRAINCENTER2_PTR_SEND_END_RESP
DATATRAINCENTER2_PTR_SEND_END_RESP -->|"unconditionally (1 cycle pulse)"| DATATRAINCENTER2_PTR_TO_LINKSPEED
DATATRAINCENTER2_PTR_TO_LINKSPEED -->|"datatraincenter2_en == 0"| END2
