// MBTRAIN.RXDESKEW FSM states:
// S0. RXDESKEW_IDLE
// S1. RXDESKEW_START_REQ_RESP
// S2. RXDESKEW_CHOOSE_PRESET
// S3. RXDESKEW_PRESET_REQ_RESP
// S4. RXDESKEW_SET_CODE
// S5. RXDESKEW_RX_D2C_PT
// S6. RXDESKEW_LOG_RESULT
// S7. RXDESKEW_CALC_APPLY
// S8. RXDESKEW_EXIT_TO_DTC1_REQ_RESP
// S9. RXDESKEW_ARC_COUNT
// S10. TO_DTC1
// S11. RXDESKEW_END_REQ_RESP
// S12. TO_DTC2
// S13. TO_TRAINERROR

module unit_RXDESKEW (


    );



endmodule